services:
  console:
    build:
      context: "."
      dockerfile: ".docker/Dockerfile"
    command: [ "while true; do sleep 1; done" ]
    entrypoint: [ "/bin/sh", "-c" ]
    logging:
      options:
        max-file: '1'
        max-size: '1m'
    stdin_open: true
    tty: true
    volumes:
      - '${PWD}:/mnt/app'
      - '${HOME}/.ssh:/home/code/.ssh:ro'
